# Collect Config #

# plugin: true or false | to disable plugin #
plugin: true

# textuters is a list of strings that will... #
textures:
  - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTY4MGI1YzY2YTk0ZjUwOTYyMDUzZjQxZGYxMmQ1OTQ0MjNkZWI3ZTQ3YzdjNjQ5Y2U3ZTE5Y2UzNjdkY2UyNiJ9fX0=
  - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWU1YmRiMGZjOTYzNzcyODM2NjUzYTcxNmVhZDVmZGYyYjc0YjRmMTA0NzFiYTgzMTVhMjA1ZDY3NWY0NzMwMSJ9fX0=
  - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmEwZjdkNjA1NTQzMTE4NGNlMDcyM2JlOTQ3ODNkOGUzZTAxMDIzNmVlMzA1MGM4OGU2N2ZjMDdkNjAyYWMxMyJ9fX0=
  - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTAzMGI0OTcwNmE2NTZkZThhMTA4YjIxNTExOTFmNDRiZTYwZDMyOGVlZDI4MmU5Y2M2ZGQ5N2M4ODJiZWQxOSJ9fX0=
